  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    ports:
      - "8080:80"  # Expose port 8080 on host and forward to port 80 in the container (HTTP)
      - "443:443"  # Expose port 443 on host and forward to port 443 in the container (HTTPS)
    volumes:
      - ./ssl:/etc/nginx/ssl  # Mount the SSL certificate files
      - ./nginx.conf:/etc/nginx/nginx.conf  # NGINX config file
      - wordpress_data:/var/www/html  # Mount WordPress data to NGINX container